### ISSUE TITLE
Save passwords as hash

### ISSUE THREAD

**Issue by NathanKeyzer** [StanBankras/amatch#15]
https://github.com/StanBankras/amatch/blob/940324ca59f87fbf89a13e5ce71cf6ce98e437de/routes/authentication.js#L47

Currently you are saving passwords as plain text. This is a security issue when your db get hacked. 
Consider hashing passwords with a library like [bcrypt](https://github.com/kelektiv/node.bcrypt.js#usage).

**Comment by HappyPantss** [comment]
Thanks Nathan for the suggestion, I will do some research about hashing passwords, and will consider to use it!

**Comment by HappyPantss** [comment]
Hashing the passwords by adding your account, and logging in with the password works. I used bcrypt.
