### ISSUE TITLE
Don't put non-middleware functions in middleware folder

### ISSUE THREAD

**Issue by follywolly** [StanBankras/amatch#16]
## Issue location
https://github.com/StanBankras/amatch/blob/311be7acfd5dc218ab5c6fa145851a3748fe4b10/routes/login.js#L24

## Issue description
The file [slug.js](https://github.com/StanBankras/amatch/blob/master/middleware/slug.js) is not a middleware function.

Although this is not really a problem, it will make it harder for other developers to understand your code. A big part of making sure your code is understandable is to use patterns the way they are supposed to be used.

I like the definition for express middleware by [LuLeBe on hackernoon](https://hackernoon.com/middleware-the-core-of-node-js-apps-ab01fee39200):

> Middleware is run before your route Handler is executed. ( ... )
> A middleware is basically a function that will the receive the Request and Response objects, just like your route Handlers do. As a third argument you have another function which you should call once your middleware code completed. 

So, by definition, the file [authentication.js](https://github.com/StanBankras/amatch/blob/master/middleware/authentication.js) in the same folder **is** a middleware function. It comes before handeling routes that require the user to be authenticated.

## How to resolve
This leaves the question, what is the pattern that the function from file `slug.js` falls in?
The function doesn't really fall in any pattern (Like routes, controllers, models, middleware). Usually, these functions end up in a `/helpers` folder or `/helpers.js` file. Sometimes, people like to put these in a `/lib` folder as well. Whatever you choose, I suggest moving the file away from the middleware folder.

## Disclaimer
Please think about every opened issue and decide wether or not you want to do anything with it. It's not important to do it my way, it's important to *be able to explain what you did or didn't do with it and why*.

**Comment by StanBankras** [comment]
Moved slug from middleware to helpers. After reviewing the definition of middleware, I completely understand why it wasn't logical to put it in the middleware folder.
