### ISSUE TITLE
Break big functions into smaller ones to improve code readability

### ISSUE THREAD

**Issue by follywolly** [StanBankras/amatch#17]
## Issue location
https://github.com/StanBankras/amatch/blob/311be7acfd5dc218ab5c6fa145851a3748fe4b10/routes/chatting.js#L17-L45

## Issue topics
- Code readability

## Issue description
This function is getting really hard to read, because a lot is going on.

## How to resolve
Split the function into multiple smaller functions that handle different parts.
I'll provide one of the parts as example.

We'll move the following part to its own function:
```js
    // ... rest
    const chatList = []; 
    user.chats.forEach((chat, err) => { 
      if(err) { 
          console.error(err); 
      } 
      chatList.push(db.collection('chats').findOne({ chatNumber: chat })); 
    }); 
    allChats = await Promise.all(chatList);
    // ... rest
```

```js
function getUserChats(user) {
  const chatList = []
  // I removed the error handling since .forEach() is a native js function and doesn't receive errors
  user.chats.forEach(chat => {  
    chatList.push(db.collection('chats').findOne({ chatNumber: chat })); 
  }); 
  return Promise.all(chatList);
}
```

You can now get the user chats in the route handler:
```js
// declare getUserChats somewhere here

router.get('/chats', auth, async (req, res) => {
  try {
    const user = await db.collection('users').findOne({ _id: ObjectID(req.session.user) });
    const allChats = await getUserChats(user)
    if (allChats.length > 0) {
    // ... rest
```
I'd suggest repeating the same for more parts in the /chats route handler.

## Disclaimer

Please think about every opened issue and decide wether or not you want to do anything with it. It's not important to do it my way, it's important to _be able to explain what you did or didn't do with it and why_.

**Comment by StanBankras** [comment]
Broke big functions down into smaller ones and this made the code a lot more readable.
