### ISSUE TITLE
Double check function consistency

### ISSUE THREAD

**Issue by follywolly** [StanBankras/amatch#18]
## Issue location
https://github.com/StanBankras/amatch/blob/311be7acfd5dc218ab5c6fa145851a3748fe4b10/services/chatService.js#L4-L11

## Issue topics

- Code consistency
- Code readability

## Issue description
Mixed use of `function(){}` syntax and `() => {}` syntax.

Although not really a problem, it's important to be able to explain your thinking about choosing when to use `function _name_() {}` and when to use `const _name_ = () => {}`. Make sure to be able to explain your choice of syntax.

Generally I suggest people to use *either* the standard `function(){}` syntax *or* the arrow `() => {}` syntax. 
Most important is that when/if you choose a main pattern, and you make exceptions to it, *be able to explain why*.

There are a lot of patterns to choose from. some people like to declare top level functions as `function _name_(){}` and callback functions or internal functions as `const _name_ = () => {}`. All fine, but make sure to have reasoning.

## Disclaimer

Please think about every opened issue and decide wether or not you want to do anything with it. It's not important to do it my way, it's important to _be able to explain what you did or didn't do with it and why_.

**Comment by StanBankras** [comment]
I understand the concern, but this is the style we have decided to write our code in. Since the dbCallback is actually a callback function, we want to use an arrow function. Functions that are not necessarily callbacks like the createChat function, we want to define in the _function name()_ syntax.
