### ISSUE TITLE
Indentation of the Javascript

### ISSUE THREAD

**Issue by StanBankras** [StanBankras/amatch#26]
https://github.com/StanBankras/amatch/blob/0ac738df2ea34d443379d3f02797687282fc67ab/routes/filter.js#L79-L96

In this part of the code, you can clearly see quite big differences in indentation of the code. Make sure everything is aligned the same everywhere.

_Note it's not just this part, there are more parts in your code where I see indentation issues._

**Comment by mbergevoet** [comment]
Thanks for pointing out the indentation mistakes. I will keep it in mind next time.
