### ISSUE TITLE
Consistency in route handlers

### ISSUE THREAD

**Issue by StanBankras** [StanBankras/amatch#27]
https://github.com/StanBankras/amatch/blob/d5019e448dcde7c7e64311b9ccbac5bebbb3c522/routes/authentication.js#L81-L92

As you can see in the code above, you use a callback function instead of an arrow function directly in the get() of the route. I think you should, like with every other route handler in this file, put the function logout also as an arrow function in the get().

**Comment by HappyPantss** [comment]
Thanks for telling me Stan, I will work on this as soon as possible!

**Comment by HappyPantss** [comment]
It is an arrow function now!
